=== IFGHou/Holodeck/src_2_8/FunctionDatabase/faults.dtd
<?xml version="1.0" encoding="iso-8859-1"?>

<!ELEMENT Function (CheckResource?, MatchParams?, ChangeParams?)>
<!ATTLIST Function OverrideErrorCode CDATA #IMPLIED>
<!ATTLIST Function OverrideReturnValue CDATA #IMPLIED>
<!ATTLIST Function Name CDATA #REQUIRED>
<!ATTLIST Function PassThrough (True|False) #IMPLIED>
<!ATTLIST Function Exception CDATA #IMPLIED>
<!ATTLIST Function Allocation (GT|GTE|LT|LTE|E) #IMPLIED>

<!ELEMENT MatchParams (MatchParam+)>
<!ELEMENT ChangeParams (ChangeParam+)>

<!ELEMENT MatchParam (#PCDATA)>
<!ATTLIST MatchParam Name CDATA #REQUIRED>
<!ATTLIST MatchParam TestOperator CDATA #REQUIRED>
<!ATTLIST MatchParam TestValue CDATA #REQUIRED>
<!ATTLIST MatchParam CompareAsType CDATA #REQUIRED>
<!ATTLIST MatchParam ID CDATA #REQUIRED>

<!ELEMENT ChangeParam (#PCDATA)>
<!ATTLIST ChangeParam Name CDATA #REQUIRED>
<!ATTLIST ChangeParam TestValue CDATA #REQUIRED>
<!ATTLIST ChangeParam CompareAsType CDATA #REQUIRED>
<!ATTLIST ChangeParam ID CDATA #REQUIRED>

<!ELEMENT CheckResource (#PCDATA)>
<!ATTLIST CheckResource ParamIndex CDATA #REQUIRED>
<!ATTLIST CheckResource Exists (1|2|3) #REQUIRED>

<!ELEMENT ReturnValue (#PCDATA)>

<!ELEMENT ErrorCode (#PCDATA)>

<!ELEMENT Fault (Function*)>
<!ATTLIST Fault Name CDATA #REQUIRED>
<!ATTLIST Fault Type CDATA #REQUIRED>
<!ATTLIST Fault ReturnValue CDATA #REQUIRED>
<!ATTLIST Fault ErrorCode CDATA #REQUIRED>

<!ELEMENT Faults (Fault*)>

=== IFGHou/Holodeck/src_2_8/FunctionDatabase/faults.xml
<?xml version="1.0" ?>
<!DOCTYPE Faults SYSTEM "faults.dtd"[]>
<!-- NOTE: All comments must go above the Faults tag
	ERROR CODE VALUES - See Winerror.h for predefined values in Windows
	ERROR_FILE_NOT_FOUND = 2
	ERROR_TOO_MANY_OPEN_FILES = 4
	ERROR_ACCESS_DENIED = 5
	ERROR_WRITE_PROTECT = 19
	ERROR_CRC = 23
	ERROR_SEEK = 25
	ERROR_SHARING_VIOLATION = 32
	ERROR_LOCK_VIOLATION = 33
	ERROR_DISK_FULL = 112
	ERROR_FILE_EXISTS = 80
	ERROR_CANNOT_MAKE = 82
	ERROR_BUFFER_OVERFLOW = 111
	ERROR_INVALID_NAME = 123
	ERROR_FILE_READ_ONLY = 6009
	ERROR_PATH_NOT_FOUND = 3
	ERROR_CURRENT_DIRECTORY = 16
	ERROR_DIR_NOT_EMPTY = 145
	ERROR_FILE_CORRUPT = 1392
	ERROR_NOT_ENOUGH_MEMORY = 8
	ERROR_NOACCESS = 998
	ERROR_LOCKED = 212
	ERROR_INVALID_ADDRESS = 487
	ERROR_PAGEFILE_QUOTA = 1454
	WSAENETDOWN = 10050
	WSAEADDRINUSE = 10048
-->
<!-- RETURN VALUES
	SOCKET_ERROR = -1
	WSASYSNOTREADY = 10091
	WSAEPROCLIM = 10067
-->
<Faults>
	<Fault Name="File_Not_Found" Type="Disk" ReturnValue="0" ErrorCode="2">
		<Function Name="CopyFileA"/>
		<Function Name="CopyFileW"/>
		<Function Name="CopyFileExA"/>
		<Function Name="CopyFileExW"/>
		<Function Name="CreateFileA" OverrideReturnValue="-1">
			<MatchParams>
				<MatchParam Name="lpFileName" TestOperator="not contains" TestValue="\\."  CompareAsType="1" ID="0"/>
			</MatchParams>
		</Function>
		<Function Name="CreateFileW" OverrideReturnValue="-1">
			<MatchParams>
				<MatchParam Name="lpFileName" TestOperator="not contains" TestValue="\\."  CompareAsType="1" ID="0"/>
			</MatchParams>
		</Function>
		<Function Name="DeleteFileA"/>
		<Function Name="DeleteFileW"/>
		<Function Name="GetFileAttributesA" OverrideReturnValue="-1"/>
		<Function Name="GetFileAttributesW" OverrideReturnValue="-1"/>
		<Function Name="GetFileAttributesExA"/>
		<Function Name="GetFileAttributesExW"/>
		<Function Name="MoveFileA"/>
		<Function Name="MoveFileW"/>
		<Function Name="MoveFileExA"/>
		<Function Name="MoveFileExW"/>
		<Function Name="MoveFileWithProgressA"/>
		<Function Name="MoveFileWithProgressW"/>
		<Function Name="ReplaceFileA"/>
		<Function Name="ReplaceFileW"/>
		<Function Name="SetFileAttributesA"/>
		<Function Name="SetFileAttributesW"/>
		<Function Name="GetBinaryTypeA"/>
		<Function Name="GetBinaryTypeW"/>
		<Function Name="RemoveDirectoryA"/>
		<Function Name="RemoveDirectoryW"/>
		<Function Name="FindFirstFileA" OverrideReturnValue="-1"/>
		<Function Name="FindFirstFileW" OverrideReturnValue="-1"/>
		<Function Name="FindFirstFileExA" OverrideReturnValue="-1"/>
		<Function Name="FindFirstFileExW" OverrideReturnValue="-1"/>
		<Function Name="FindNextFileA" OverrideErrorCode="18"/>
		<Function Name="FindNextFileW" OverrideErrorCode="18"/>
		<Function Name="FindFirstChangeNotificationA" OverrideReturnValue="-1"/>
		<Function Name="FindFirstChangeNotificationW" OverrideReturnValue="-1"/>
		<Function Name="SearchPathA"/>
		<Function Name="SearchPathW"/>
		<Function Name="OpenFileMappingA"/>
		<Function Name="OpenFileMappingW"/>
	</Fault>
	<Fault Name="Too_Many_Open_Files" Type="Disk" ReturnValue="-1" ErrorCode="4">
		<Function Name="CreateFileA">
			<MatchParams>
				<MatchParam Name="lpFileName" TestOperator="not contains" TestValue="\\."  CompareAsType="1" ID="0"/>
			</MatchParams>
		</Function>
		<Function Name="CreateFileW">
			<MatchParams>
				<MatchParam Name="lpFileName" TestOperator="not contains" TestValue="\\."  CompareAsType="1" ID="0"/>
			</MatchParams>
		</Function>
		<Function Name="FindFirstFileA"/>
		<Function Name="FindFirstFileW"/>
		<Function Name="FindFirstFileExA"/>
		<Function Name="FindFirstFileExW"/>
		<Function Name="OpenFileMappingA" OverrideReturnValue="0"/>
		<Function Name="OpenFileMappingW" OverrideReturnValue="0"/>
	</Fault>
	<Fault Name="Access_Denied_To_File" Type="Disk" ReturnValue="0" ErrorCode="5">
		<Function Name="CopyFileA"/>
		<Function Name="CopyFileW"/>
		<Function Name="CopyFileExA"/>
		<Function Name="CopyFileExW"/>
		<Function Name="CreateFileA" OverrideReturnValue="-1">
			<MatchParams>
				<MatchParam Name="lpFileName" TestOperator="not contains" TestValue="\\."  CompareAsType="1" ID="0"></MatchParam>
			</MatchParams>
		</Function>
		<Function Name="CreateFileW" OverrideReturnValue="-1">
			<MatchParams>
				<MatchParam Name="lpFileName" TestOperator="not contains" TestValue="\\."  CompareAsType="1" ID="0"/>
			</MatchParams>
		</Function>
		<Function Name="DeleteFileA"/>
		<Function Name="DeleteFileW"/>
		<Function Name="GetFileAttributesA" OverrideReturnValue="-1"/>
		<Function Name="GetFileAttributesW" OverrideReturnValue="-1"/>
		<Function Name="GetFileAttributesExA"/>
		<Function Name="GetFileAttributesExW"/>
		<Function Name="MoveFileA"/>
		<Function Name="MoveFileW"/>
		<Function Name="MoveFileExA"/>
		<Function Name="MoveFileExW"/>
		<Function Name="MoveFileWithProgressA"/>
		<Function Name="MoveFileWithProgressW"/>
		<Function Name="ReplaceFileA"/>
		<Function Name="ReplaceFileW"/>
		<Function Name="SetFileAttributesA"/>
		<Function Name="SetFileAttributesW"/>
		<Function Name="CreateDirectoryA"/>
		<Function Name="CreateDirectoryW"/>
		<Function Name="CreateDirectoryExA"/>
		<Function Name="CreateDirectoryExW"/>
		<Function Name="GetCurrentDirectoryA"/>
		<Function Name="GetCurrentDirectoryW"/>
		<Function Name="GetDiskFreeSpaceA"/>
		<Function Name="GetDiskFreeSpaceW"/>
		<Function Name="GetDiskFreeSpaceExA"/>
		<Function Name="GetDiskFreeSpaceExW"/>
		<Function Name="GetDriveTypeA"/>
		<Function Name="GetDriveTypeW"/>
		<Function Name="GetFileSize" OverrideReturnValue="-1"/>
		<Function Name="GetFileSizeEx"/>
		<Function Name="GetLogicalDrives"/>
		<Function Name="GetLogicalDriveStringsA"/>
		<Function Name="GetLogicalDriveStringsW"/>
		<Function Name="GetBinaryTypeA"/>
		<Function Name="GetBinaryTypeW"/>
		<Function Name="RemoveDirectoryA"/>
		<Function Name="RemoveDirectoryW"/>
		<Function Name="DefineDosDeviceA"/>
		<Function Name="DefineDosDeviceW"/>
		<Function Name="FindFirstFileA" OverrideReturnValue="-1"/>
		<Function Name="FindFirstFileW" OverrideReturnValue="-1"/>
		<Function Name="FindFirstFileExA" OverrideReturnValue="-1"/>
		<Function Name="FindFirstFileExW" OverrideReturnValue="-1"/>
		<Function Name="FindNextFileA"/>
		<Function Name="FindNextFileW"/>
		<Function Name="FindFirstChangeNotificationA" OverrideReturnValue="-1"/>
		<Function Name="FindFirstChangeNotificationW" OverrideReturnValue="-1"/>
		<Function Name="GetFileInformationByHandle"/>
		<Function Name="QueryDosDeviceA"/>
		<Function Name="QueryDosDeviceW"/>
		<Function Name="ReadDirectoryChangesA"/>
		<Function Name="ReadDirectoryChangesW"/>
		<Function Name="ReadFile"/>
		<Function Name="ReadFileEx"/>
		<Function Name="ReadFileScatter"/>
		<Function Name="SearchPathA"/>
		<Function Name="SearchPathW"/>
		<Function Name="SetFileSecurityA"/>
		<Function Name="SetFileSecurityW"/>
		<Function Name="SetFileShortNameA"/>
		<Function Name="SetFileShortNameW"/>
		<Function Name="SetFileValidData"/>
		<Function Name="SetVolumeLabelA"/>
		<Function Name="SetVolumeLabelW"/>
		<Function Name="LockFile"/>
		<Function Name="LockFileEx"/>
		<Function Name="UnlockFile"/>
		<Function Name="UnlockFileEx"/>
		<Function Name="GetTempPathA"/>
		<Function Name="GetTempPathW"/>
		<Function Name="FlushFileBuffers"/>
		<Function Name="SetEndOfFile"/>
		<Function Name="SetFilePointer" OverrideReturnValue="-1"/>
		<Function Name="SetFilePointerEx"/>
		<Function Name="WriteFile"/>
		<Function Name="WriteFileEx"/>
		<Function Name="WriteFileGather"/>
		<Function Name="OpenFileMappingA"/>
		<Function Name="OpenFileMappingW"/>
		<Function Name="CreateFileMappingA"/>
		<Function Name="CreateFileMappingW"/>
		<Function Name="MapViewOfFile"/>
		<Function Name="MapViewOfFileEx"/>
	</Fault>
	<Fault Name="File_Is_Read_Only" Type="Disk" ReturnValue="0" ErrorCode="6009">
		<Function Name="CopyFileA"/>
		<Function Name="CopyFileW"/>
		<Function Name="CopyFileExA"/>
		<Function Name="CopyFileExW"/>
		<Function Name="CreateFileA" OverrideReturnValue="-1">
			<MatchParams>
				<MatchParam Name="lpFileName" TestOperator="not contains" TestValue="\\."  CompareAsType="1" ID="0"/>
				<MatchParam Name="dwDesiredAccess" TestOperator="!=" TestValue="2147483648"  CompareAsType="5" ID="1"/>
			</MatchParams>
		</Function>
		<Function Name="CreateFileW" OverrideReturnValue="-1">
			<MatchParams>
				<MatchParam Name="lpFileName" TestOperator="not contains" TestValue="\\."  CompareAsType="1" ID="0"/>
				<MatchParam Name="dwDesiredAccess" TestOperator="!=" TestValue="2147483648"  CompareAsType="5" ID="1"/>
			</MatchParams>
		</Function>
		<Function Name="DeleteFileA"/>
		<Function Name="DeleteFileW"/>
		<Function Name="MoveFileA"/>
		<Function Name="MoveFileW"/>
		<Function Name="MoveFileExA"/>
		<Function Name="MoveFileExW"/>
		<Function Name="MoveFileWithProgressA"/>
		<Function Name="MoveFileWithProgressW"/>
		<Function Name="ReplaceFileA"/>
		<Function Name="ReplaceFileW"/>
		<Function Name="SetFileAttributesA"/>
		<Function Name="SetFileAttributesW"/>
		<Function Name="CreateDirectoryA"/>
		<Function Name="CreateDirectoryW"/>
		<Function Name="CreateDirectoryExA"/>
		<Function Name="CreateDirectoryExW"/>
		<Function Name="RemoveDirectoryA"/>
		<Function Name="RemoveDirectoryW"/>
		<Function Name="SetEndOfFile"/>
		<Function Name="SetFilePointer" OverrideReturnValue="-1"/>
		<Function Name="SetFilePointerEx"/>
		<Function Name="WriteFile"/>
		<Function Name="WriteFileEx"/>
		<Function Name="WriteFileGather"/>
		<Function Name="SetFileShortNameA"/>
		<Function Name="SetFileShortNameW"/>
		<Function Name="SetFileValidData"/>
		<Function Name="FlushFileBuffers"/>
		<Function Name="LockFile"/>
		<Function Name="LockFileEx"/>
		<Function Name="UnlockFile"/>
