=== IFGHou/Holodeck/src/FunctionDatabase/Exceptions.dtd
<?xml version="1.0" encoding="iso-8859-1"?>

<!ELEMENT Exception (#PCDATA)>
<!ATTLIST Exception Name CDATA #REQUIRED>

<!ELEMENT Exceptions (Exception*)>

=== IFGHou/Holodeck/src_2_8/FunctionDatabase/Exceptions.xml
<?xml version="1.0" ?>
<!DOCTYPE Exceptions SYSTEM "Exceptions.dtd"[]>
<Exceptions>
	<Exception Name="System.ServiceProcess.TimeoutException" />
	<Exception Name="System.Xml.XmlException" />
	<Exception Name="System.Xml.XPath.XPathException" />
	<Exception Name="System.Xml.Xsl.XsltException" />
	<Exception Name="System.Xml.Xsl.XsltCompileException" />
	<Exception Name="System.Xml.Schema.XmlSchemaException" />
	<Exception Name="System.ComponentModel.LicenseException" />
	<Exception Name="System.ComponentModel.InvalidEnumArgumentException" />
	<Exception Name="System.ComponentModel.WarningException" />
	<Exception Name="System.ComponentModel.Win32Exception" />
	<Exception Name="System.ComponentModel.Design.CheckoutException" />
	<Exception Name="System.UriFormatException" />
	<Exception Name="System.Net.CookieException" />
	<Exception Name="System.Net.ProtocolViolationException" />
	<Exception Name="System.Net.Sockets.SocketException" />
	<Exception Name="System.Net.WebException" />
	<Exception Name="System.Configuration.ConfigurationException" />
	<Exception Name="System.IO.InternalBufferOverflowException" />
	<Exception Name="System.SystemException" />
	<Exception Name="System.OutOfMemoryException" />
	<Exception Name="System.StackOverflowException" />
	<Exception Name="System.ExecutionEngineException" />
	<Exception Name="System.MemberAccessException" />
	<Exception Name="System.ApplicationException" />
	<Exception Name="System.AppDomainUnloadedException" />
	<Exception Name="System.ArgumentException" />
	<Exception Name="System.ArgumentNullException" />
	<Exception Name="System.ArgumentOutOfRangeException" />
	<Exception Name="System.ArithmeticException" />
	<Exception Name="System.ArrayTypeMismatchException" />
	<Exception Name="System.BadImageFormatException" />
	<Exception Name="System.CannotUnloadAppDomainException" />
	<Exception Name="System.TypeUnloadedException" />
	<Exception Name="System.ContextMarshalException" />
	<Exception Name="System.DivideByZeroException" />
	<Exception Name="System.DuplicateWaitObjectException" />
	<Exception Name="System.TypeLoadException" />
	<Exception Name="System.EntryPointNotFoundException" />
	<Exception Name="System.DllNotFoundException" />
	<Exception Name="System.FieldAccessException" />
	<Exception Name="System.FormatException" />
	<Exception Name="System.IndexOutOfRangeException" />
	<Exception Name="System.InvalidCastException" />
	<Exception Name="System.InvalidOperationException" />
	<Exception Name="System.InvalidProgramException" />
	<Exception Name="System.MethodAccessException" />
	<Exception Name="System.MissingMemberException" />
	<Exception Name="System.MissingFieldException" />
	<Exception Name="System.MissingMethodException" />
	<Exception Name="System.MulticastNotSupportedException" />
	<Exception Name="System.NotFiniteNumberException" />
	<Exception Name="System.NotImplementedException" />
	<Exception Name="System.NotSupportedException" />
	<Exception Name="System.NullReferenceException" />
	<Exception Name="System.ObjectDisposedException" />
	<Exception Name="System.OverflowException" />
	<Exception Name="System.PlatformNotSupportedException" />
	<Exception Name="System.RankException" />
	<Exception Name="System.TypeInitializationException" />
	<Exception Name="System.UnauthorizedAccessException" />
	<Exception Name="System.Threading.SynchronizationLockException" />
	<Exception Name="System.Threading.ThreadAbortException" />
	<Exception Name="System.Threading.ThreadInterruptedException" />
	<Exception Name="System.Threading.ThreadStateException" />
	<Exception Name="System.Reflection.AmbiguousMatchException" />
	<Exception Name="System.Reflection.CustomAttributeFormatException" />
	<Exception Name="System.Reflection.InvalidFilterCriteriaException" />
	<Exception Name="System.Reflection.ReflectionTypeLoadException" />
	<Exception Name="System.Reflection.TargetException" />
	<Exception Name="System.Reflection.TargetInvocationException" />
	<Exception Name="System.Reflection.TargetParameterCountException" />
	<Exception Name="System.Runtime.Serialization.SerializationException" />
	<Exception Name="System.Resources.MissingManifestResourceException" />
	<Exception Name="System.Security.Cryptography.CryptographicException" />
	<Exception Name="System.Security.Cryptography.CryptographicUnexpectedOperationException" />
	<Exception Name="System.Security.Policy.PolicyException" />
	<Exception Name="System.Runtime.InteropServices.ExternalException" />
	<Exception Name="System.Runtime.InteropServices.COMException" />
	<Exception Name="System.Runtime.InteropServices.InvalidComObjectException" />
	<Exception Name="System.Runtime.InteropServices.InvalidOleVariantTypeException" />
	<Exception Name="System.Runtime.InteropServices.MarshalDirectiveException" />
	<Exception Name="System.Runtime.InteropServices.SafeArrayRankMismatchException" />
	<Exception Name="System.Runtime.InteropServices.SafeArrayTypeMismatchException" />
	<Exception Name="System.Runtime.InteropServices.SEHException" />
	<Exception Name="System.IO.IOException" />
	<Exception Name="System.IO.DirectoryNotFoundException" />
	<Exception Name="System.IO.EndOfStreamException" />
	<Exception Name="System.IO.FileLoadException" />
	<Exception Name="System.IO.FileNotFoundException" />
	<Exception Name="System.IO.PathTooLongException" />
	<Exception Name="System.Security.XmlSyntaxException" />
	<Exception Name="System.Security.SecurityException" />
	<Exception Name="System.Security.VerificationException" />
	<Exception Name="System.Runtime.Remoting.RemotingException" />
	<Exception Name="System.Runtime.Remoting.ServerException" />
	<Exception Name="System.Runtime.Remoting.RemotingTimeoutException" />
	<Exception Name="System.IO.IsolatedStorage.IsolatedStorageException" />
</Exceptions>
