=== IFGHou/Holodeck/src/Tools/FrameworkUpdate/FunctionDatabase/ErrorCodes.dtd
<?xml version="1.0" encoding="iso-8859-1"?>

<!ELEMENT ErrorCode (#PCDATA)>
<!ATTLIST ErrorCode Code CDATA #REQUIRED>
<!ATTLIST ErrorCode String CDATA #REQUIRED>

<!ELEMENT ErrorCodes (ErrorCode*)>

=== IFGHou/Holodeck/src_2_8/FunctionDatabase/ErrorCodes.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE ErrorCodes SYSTEM "ErrorCodes.dtd"[]>
<ErrorCodes>
<ErrorCode Code="0" String="ERROR_SUCCESS"></ErrorCode>
<ErrorCode Code="1" String="ERROR_INVALID_FUNCTION"></ErrorCode>
<ErrorCode Code="2" String="ERROR_FILE_NOT_FOUND"></ErrorCode>
<ErrorCode Code="3" String="ERROR_PATH_NOT_FOUND"></ErrorCode>
<ErrorCode Code="4" String="ERROR_TOO_MANY_OPEN_FILES"></ErrorCode>
<ErrorCode Code="5" String="ERROR_ACCESS_DENIED"></ErrorCode>
<ErrorCode Code="6" String="ERROR_INVALID_HANDLE"></ErrorCode>
<ErrorCode Code="7" String="ERROR_ARENA_TRASHED"></ErrorCode>
<ErrorCode Code="8" String="ERROR_NOT_ENOUGH_MEMORY"></ErrorCode>
<ErrorCode Code="9" String="ERROR_INVALID_BLOCK"></ErrorCode>
<ErrorCode Code="10" String="ERROR_BAD_ENVIRONMENT"></ErrorCode>
<ErrorCode Code="11" String="ERROR_BAD_FORMAT"></ErrorCode>
<ErrorCode Code="12" String="ERROR_INVALID_ACCESS"></ErrorCode>
<ErrorCode Code="13" String="ERROR_INVALID_DATA"></ErrorCode>
<ErrorCode Code="14" String="ERROR_OUTOFMEMORY"></ErrorCode>
<ErrorCode Code="15" String="ERROR_INVALID_DRIVE"></ErrorCode>
<ErrorCode Code="16" String="ERROR_CURRENT_DIRECTORY"></ErrorCode>
<ErrorCode Code="17" String="ERROR_NOT_SAME_DEVICE"></ErrorCode>
<ErrorCode Code="18" String="ERROR_NO_MORE_FILES"></ErrorCode>
<ErrorCode Code="19" String="ERROR_WRITE_PROTECT"></ErrorCode>
<ErrorCode Code="20" String="ERROR_BAD_UNIT"></ErrorCode>
<ErrorCode Code="21" String="ERROR_NOT_READY"></ErrorCode>
<ErrorCode Code="22" String="ERROR_BAD_COMMAND"></ErrorCode>
<ErrorCode Code="23" String="ERROR_CRC"></ErrorCode>
<ErrorCode Code="24" String="ERROR_BAD_LENGTH"></ErrorCode>
<ErrorCode Code="25" String="ERROR_SEEK"></ErrorCode>
<ErrorCode Code="26" String="ERROR_NOT_DOS_DISK"></ErrorCode>
<ErrorCode Code="27" String="ERROR_SECTOR_NOT_FOUND"></ErrorCode>
<ErrorCode Code="28" String="ERROR_OUT_OF_PAPER"></ErrorCode>
<ErrorCode Code="29" String="ERROR_WRITE_FAULT"></ErrorCode>
<ErrorCode Code="30" String="ERROR_READ_FAULT"></ErrorCode>
<ErrorCode Code="31" String="ERROR_GEN_FAILURE"></ErrorCode>
<ErrorCode Code="32" String="ERROR_SHARING_VIOLATION"></ErrorCode>
<ErrorCode Code="33" String="ERROR_LOCK_VIOLATION"></ErrorCode>
<ErrorCode Code="34" String="ERROR_WRONG_DISK"></ErrorCode>
<ErrorCode Code="36" String="ERROR_SHARING_BUFFER_EXCEEDED"></ErrorCode>
<ErrorCode Code="38" String="ERROR_HANDLE_EOF"></ErrorCode>
<ErrorCode Code="39" String="ERROR_HANDLE_DISK_FULL"></ErrorCode>
<ErrorCode Code="50" String="ERROR_NOT_SUPPORTED"></ErrorCode>
<ErrorCode Code="51" String="ERROR_REM_NOT_LIST"></ErrorCode>
<ErrorCode Code="52" String="ERROR_DUP_NAME"></ErrorCode>
<ErrorCode Code="53" String="ERROR_BAD_NETPATH"></ErrorCode>
<ErrorCode Code="54" String="ERROR_NETWORK_BUSY"></ErrorCode>
<ErrorCode Code="55" String="ERROR_DEV_NOT_EXIST"></ErrorCode>
<ErrorCode Code="56" String="ERROR_TOO_MANY_CMDS"></ErrorCode>
<ErrorCode Code="57" String="ERROR_ADAP_HDW_ERR"></ErrorCode>
<ErrorCode Code="58" String="ERROR_BAD_NET_RESP"></ErrorCode>
<ErrorCode Code="59" String="ERROR_UNEXP_NET_ERR"></ErrorCode>
<ErrorCode Code="60" String="ERROR_BAD_REM_ADAP"></ErrorCode>
<ErrorCode Code="61" String="ERROR_PRINTQ_FULL"></ErrorCode>
<ErrorCode Code="62" String="ERROR_NO_SPOOL_SPACE"></ErrorCode>
<ErrorCode Code="63" String="ERROR_PRINT_CANCELLED"></ErrorCode>
<ErrorCode Code="64" String="ERROR_NETNAME_DELETED"></ErrorCode>
<ErrorCode Code="65" String="ERROR_NETWORK_ACCESS_DENIED"></ErrorCode>
<ErrorCode Code="66" String="ERROR_BAD_DEV_TYPE"></ErrorCode>
<ErrorCode Code="67" String="ERROR_BAD_NET_NAME"></ErrorCode>
<ErrorCode Code="68" String="ERROR_TOO_MANY_NAMES"></ErrorCode>
<ErrorCode Code="69" String="ERROR_TOO_MANY_SESS"></ErrorCode>
<ErrorCode Code="70" String="ERROR_SHARING_PAUSED"></ErrorCode>
<ErrorCode Code="71" String="ERROR_REQ_NOT_ACCEP"></ErrorCode>
<ErrorCode Code="72" String="ERROR_REDIR_PAUSED"></ErrorCode>
<ErrorCode Code="80" String="ERROR_FILE_EXISTS"></ErrorCode>
<ErrorCode Code="82" String="ERROR_CANNOT_MAKE"></ErrorCode>
<ErrorCode Code="83" String="ERROR_FAIL_I24"></ErrorCode>
<ErrorCode Code="84" String="ERROR_OUT_OF_STRUCTURES"></ErrorCode>
<ErrorCode Code="85" String="ERROR_ALREADY_ASSIGNED"></ErrorCode>
<ErrorCode Code="86" String="ERROR_INVALID_PASSWORD"></ErrorCode>
<ErrorCode Code="87" String="ERROR_INVALID_PARAMETER"></ErrorCode>
<ErrorCode Code="88" String="ERROR_NET_WRITE_FAULT"></ErrorCode>
<ErrorCode Code="89" String="ERROR_NO_PROC_SLOTS"></ErrorCode>
<ErrorCode Code="100" String="ERROR_TOO_MANY_SEMAPHORES"></ErrorCode>
<ErrorCode Code="101" String="ERROR_EXCL_SEM_ALREADY_OWNED"></ErrorCode>
<ErrorCode Code="102" String="ERROR_SEM_IS_SET"></ErrorCode>
<ErrorCode Code="103" String="ERROR_TOO_MANY_SEM_REQUESTS"></ErrorCode>
<ErrorCode Code="104" String="ERROR_INVALID_AT_INTERRUPT_TIME"></ErrorCode>
<ErrorCode Code="105" String="ERROR_SEM_OWNER_DIED"></ErrorCode>
<ErrorCode Code="106" String="ERROR_SEM_USER_LIMIT"></ErrorCode>
<ErrorCode Code="107" String="ERROR_DISK_CHANGE"></ErrorCode>
<ErrorCode Code="108" String="ERROR_DRIVE_LOCKED"></ErrorCode>
<ErrorCode Code="109" String="ERROR_BROKEN_PIPE"></ErrorCode>
<ErrorCode Code="110" String="ERROR_OPEN_FAILED"></ErrorCode>
<ErrorCode Code="111" String="ERROR_BUFFER_OVERFLOW"></ErrorCode>
<ErrorCode Code="112" String="ERROR_DISK_FULL"></ErrorCode>
<ErrorCode Code="113" String="ERROR_NO_MORE_SEARCH_HANDLES"></ErrorCode>
<ErrorCode Code="114" String="ERROR_INVALID_TARGET_HANDLE"></ErrorCode>
<ErrorCode Code="117" String="ERROR_INVALID_CATEGORY"></ErrorCode>
<ErrorCode Code="118" String="ERROR_INVALID_VERIFY_SWITCH"></ErrorCode>
<ErrorCode Code="119" String="ERROR_BAD_DRIVER_LEVEL"></ErrorCode>
<ErrorCode Code="120" String="ERROR_CALL_NOT_IMPLEMENTED"></ErrorCode>
<ErrorCode Code="121" String="ERROR_SEM_TIMEOUT"></ErrorCode>
<ErrorCode Code="122" String="ERROR_INSUFFICIENT_BUFFER"></ErrorCode>
<ErrorCode Code="123" String="ERROR_INVALID_NAME"></ErrorCode>
<ErrorCode Code="124" String="ERROR_INVALID_LEVEL"></ErrorCode>
<ErrorCode Code="125" String="ERROR_NO_VOLUME_LABEL"></ErrorCode>
<ErrorCode Code="126" String="ERROR_MOD_NOT_FOUND"></ErrorCode>
<ErrorCode Code="127" String="ERROR_PROC_NOT_FOUND"></ErrorCode>
<ErrorCode Code="128" String="ERROR_WAIT_NO_CHILDREN"></ErrorCode>
<ErrorCode Code="129" String="ERROR_CHILD_NOT_COMPLETE"></ErrorCode>
<ErrorCode Code="130" String="ERROR_DIRECT_ACCESS_HANDLE"></ErrorCode>
<ErrorCode Code="131" String="ERROR_NEGATIVE_SEEK"></ErrorCode>
<ErrorCode Code="132" String="ERROR_SEEK_ON_DEVICE"></ErrorCode>
<ErrorCode Code="133" String="ERROR_IS_JOIN_TARGET"></ErrorCode>
<ErrorCode Code="134" String="ERROR_IS_JOINED"></ErrorCode>
<ErrorCode Code="135" String="ERROR_IS_SUBSTED"></ErrorCode>
<ErrorCode Code="136" String="ERROR_NOT_JOINED"></ErrorCode>
<ErrorCode Code="137" String="ERROR_NOT_SUBSTED"></ErrorCode>
<ErrorCode Code="138" String="ERROR_JOIN_TO_JOIN"></ErrorCode>
<ErrorCode Code="139" String="ERROR_SUBST_TO_SUBST"></ErrorCode>
<ErrorCode Code="140" String="ERROR_JOIN_TO_SUBST"></ErrorCode>
<ErrorCode Code="141" String="ERROR_SUBST_TO_JOIN"></ErrorCode>
<ErrorCode Code="142" String="ERROR_BUSY_DRIVE"></ErrorCode>
<ErrorCode Code="143" String="ERROR_SAME_DRIVE"></ErrorCode>
<ErrorCode Code="144" String="ERROR_DIR_NOT_ROOT"></ErrorCode>
<ErrorCode Code="145" String="ERROR_DIR_NOT_EMPTY"></ErrorCode>
<ErrorCode Code="146" String="ERROR_IS_SUBST_PATH"></ErrorCode>
<ErrorCode Code="147" String="ERROR_IS_JOIN_PATH"></ErrorCode>
<ErrorCode Code="148" String="ERROR_PATH_BUSY"></ErrorCode>
<ErrorCode Code="149" String="ERROR_IS_SUBST_TARGET"></ErrorCode>
<ErrorCode Code="150" String="ERROR_SYSTEM_TRACE"></ErrorCode>
<ErrorCode Code="151" String="ERROR_INVALID_EVENT_COUNT"></ErrorCode>
<ErrorCode Code="152" String="ERROR_TOO_MANY_MUXWAITERS"></ErrorCode>
<ErrorCode Code="153" String="ERROR_INVALID_LIST_FORMAT"></ErrorCode>
<ErrorCode Code="154" String="ERROR_LABEL_TOO_LONG"></ErrorCode>
<ErrorCode Code="155" String="ERROR_TOO_MANY_TCBS"></ErrorCode>
<ErrorCode Code="156" String="ERROR_SIGNAL_REFUSED"></ErrorCode>
<ErrorCode Code="157" String="ERROR_DISCARDED"></ErrorCode>
<ErrorCode Code="158" String="ERROR_NOT_LOCKED"></ErrorCode>
<ErrorCode Code="159" String="ERROR_BAD_THREADID_ADDR"></ErrorCode>
<ErrorCode Code="160" String="ERROR_BAD_ARGUMENTS"></ErrorCode>
<ErrorCode Code="161" String="ERROR_BAD_PATHNAME"></ErrorCode>
<ErrorCode Code="162" String="ERROR_SIGNAL_PENDING"></ErrorCode>
<ErrorCode Code="164" String="ERROR_MAX_THRDS_REACHED"></ErrorCode>
<ErrorCode Code="167" String="ERROR_LOCK_FAILED"></ErrorCode>
<ErrorCode Code="170" String="ERROR_BUSY"></ErrorCode>
<ErrorCode Code="173" String="ERROR_CANCEL_VIOLATION"></ErrorCode>
<ErrorCode Code="174" String="ERROR_ATOMIC_LOCKS_NOT_SUPPORTED"></ErrorCode>
<ErrorCode Code="180" String="ERROR_INVALID_SEGMENT_NUMBER"></ErrorCode>
<ErrorCode Code="182" String="ERROR_INVALID_ORDINAL"></ErrorCode>
<ErrorCode Code="183" String="ERROR_ALREADY_EXISTS"></ErrorCode>
<ErrorCode Code="186" String="ERROR_INVALID_FLAG_NUMBER"></ErrorCode>
<ErrorCode Code="187" String="ERROR_SEM_NOT_FOUND"></ErrorCode>
<ErrorCode Code="188" String="ERROR_INVALID_STARTING_CODESEG"></ErrorCode>
<ErrorCode Code="189" String="ERROR_INVALID_STACKSEG"></ErrorCode>
<ErrorCode Code="190" String="ERROR_INVALID_MODULETYPE"></ErrorCode>
<ErrorCode Code="191" String="ERROR_INVALID_EXE_SIGNATURE"></ErrorCode>
<ErrorCode Code="192" String="ERROR_EXE_MARKED_INVALID"></ErrorCode>
<ErrorCode Code="193" String="ERROR_BAD_EXE_FORMAT"></ErrorCode>
<ErrorCode Code="194" String="ERROR_ITERATED_DATA_EXCEEDS_64k"></ErrorCode>
<ErrorCode Code="195" String="ERROR_INVALID_MINALLOCSIZE"></ErrorCode>
<ErrorCode Code="196" String="ERROR_DYNLINK_FROM_INVALID_RING"></ErrorCode>
