=== IFGHou/Holodeck/BuildTool/SIBuilder/buildfile.dtd
<?xml version="1.0" encoding="iso-8859-1"?>

<!ELEMENT EXECUTE (#PCDATA)>
<!ATTLIST EXECUTE Args CDATA #REQUIRED>

<!ELEMENT SOURCECONTROL (EXECUTE*)>

<!ELEMENT BUILDS_LOCATION (#PCDATA)>

<!ELEMENT LOGS_LOCATION (#PCDATA)>

<!ELEMENT DEVENV_FILE (#PCDATA)>

<!ELEMENT INSTALLSHIELD_SCRIPT (#PCDATA)>

<!ELEMENT INSTALLSHIELD_OUTPUT (#PCDATA)>

<!ELEMENT PATHS (BUILDS_LOCATION, LOGS_LOCATION, DEVENV_FILE, INSTALLSHIELD_SCRIPT, INSTALLSHIELD_OUTPUT)>

<!ELEMENT RECIPIENTS (#PCDATA)>

<!ELEMENT MAILSENDER (#PCDATA)>
<!ATTLIST MAILSENDER Address CDATA #REQUIRED>
<!ATTLIST MAILSENDER SmtpServer CDATA #REQUIRED>

<!ELEMENT BUILDMAIL (RECIPIENTS, MAILSENDER)>

<!ELEMENT SOLUTION (#PCDATA)>

<!ATTLIST SOLUTION Project CDATA #REQUIRED>
<!ATTLIST SOLUTION BuildConfig (Debug|Release) #REQUIRED>

<!ELEMENT BUILD_SOLUTIONS (SOLUTION*)>

<!ELEMENT PRODUCT (SOURCECONTROL, PATHS, BUILDMAIL, BUILD_SOLUTIONS)>
<!ATTLIST PRODUCT Name CDATA #REQUIRED>
<!ATTLIST PRODUCT MajorVersion CDATA #REQUIRED>
<!ATTLIST PRODUCT MinorVersion CDATA #REQUIRED><!ATTLIST PRODUCT BuildNumber CDATA #REQUIRED>
<!ELEMENT SIBUILDER (PRODUCT*)>

=== IFGHou/Holodeck/BuildTool/SIBuilder/builderConfig.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE SIBUILDER SYSTEM "c:\sisvn\trunk\commercial\Holodeck\BuildTool\SIBuilder\BuildFile.dtd"[]>
<SIBUILDER>
  <PRODUCT Name="Holodeck 2.5 Test" MajorVersion="2" MinorVersion="5" BuildNumber="36">
    <SOURCECONTROL />
    <PATHS>
      <BUILDS_LOCATION>c:\builds\Test</BUILDS_LOCATION>
      <LOGS_LOCATION>c:\builds\Test</LOGS_LOCATION>
      <DEVENV_FILE>C:\Program Files\Microsoft Visual Studio .NET 2003\Common7\IDE\devenv.exe</DEVENV_FILE>
      <INSTALLSHIELD_SCRIPT>C:\source_code\commercial\Holodeck\Install\HolodeckEE - DevStudio\HolodeckEESetup.ism.cmd</INSTALLSHIELD_SCRIPT>
      <INSTALLSHIELD_OUTPUT>C:\source_code\commercial\Holodeck\Install\HolodeckEE - DevStudio\Media\CD-ROM Media\Package\HolodeckEESetup.exe</INSTALLSHIELD_OUTPUT>
    </PATHS>
    <BUILDMAIL>
      <RECIPIENTS>akakrania@sisecure.com</RECIPIENTS>
      <MAILSENDER Address="sibuilder@sisecure.com" SmtpServer="192.168.2.1" />
    </BUILDMAIL>
    <BUILD_SOLUTIONS>
      <SOLUTION Project="" BuildConfig="Release">C:\source_code\commercial\Holodeck\src\MasterWorkspace\Holodeck.sln</SOLUTION>
    </BUILD_SOLUTIONS>
  </PRODUCT>
  <PRODUCT Name="Holodeck 2.1 Longhorn Time Trial" MajorVersion="2" MinorVersion="1" BuildNumber="212">
    <SOURCECONTROL>
      <EXECUTE Args="/C c:\source_code\commercial\OldVersions\Holodeck\v2_1_longhorn\Install\HolodeckEESetup\unmake_trial.bat">c:\windows\system32\cmd.exe</EXECUTE>
      <EXECUTE Args="/C c:\source_code\commercial\OldVersions\Holodeck\v2_1_longhorn\Install\HolodeckEESetup\make_timetrial.bat">c:\windows\system32\cmd.exe</EXECUTE>
    </SOURCECONTROL>
    <PATHS>
      <BUILDS_LOCATION>c:\builds;y:</BUILDS_LOCATION>
      <LOGS_LOCATION>c:\builds\BuildLogs</LOGS_LOCATION>
      <DEVENV_FILE>C:\Program Files\Microsoft Visual Studio .NET Whidbey\Common7\IDE\devenv.exe</DEVENV_FILE>
      <INSTALLSHIELD_SCRIPT>C:\source_code\commercial\OldVersions\Holodeck\v2_1_longhorn\Install\HolodeckEESetup\HolodeckEESetup.ism.cmd</INSTALLSHIELD_SCRIPT>
      <INSTALLSHIELD_OUTPUT>C:\source_code\commercial\OldVersions\Holodeck\v2_1_longhorn\Install\HolodeckEESetup\Media\CD ROM Media\Package\HolodeckEESetup.exe</INSTALLSHIELD_OUTPUT>
    </PATHS>
    <BUILDMAIL>
      <RECIPIENTS>akakrania@sisecure.com, bshirey@sisecure.com, jtaylor@sisecure.com, rwagner@sisecure.com, jbasirico@sisecure.com, jwhitehouse@sisecure.com</RECIPIENTS>
      <MAILSENDER Address="sibuilder@sisecure.com" SmtpServer="192.168.2.1" />
    </BUILDMAIL>
    <BUILD_SOLUTIONS>
      <SOLUTION Project="FileCorruptionGenerator" BuildConfig="Release">C:\source_code\commercial\OldVersions\Holodeck\v2_1_longhorn\holodeck\holodeckgui\holodeckgui.sln</SOLUTION>
      <SOLUTION Project="HeatDll" BuildConfig="Release">C:\source_code\commercial\OldVersions\Holodeck\v2_1_longhorn\holodeck\holodeckgui\holodeckgui.sln</SOLUTION>
      <SOLUTION Project="HeatApi" BuildConfig="Release">C:\source_code\commercial\OldVersions\Holodeck\v2_1_longhorn\holodeck\holodeckgui\holodeckgui.sln</SOLUTION>
      <SOLUTION Project="SiUtils" BuildConfig="Release">C:\source_code\commercial\OldVersions\Holodeck\v2_1_longhorn\holodeck\holodeckgui\holodeckgui.sln</SOLUTION>
      <SOLUTION Project="FunctionDatabase" BuildConfig="Release">C:\source_code\commercial\OldVersions\Holodeck\v2_1_longhorn\holodeck\holodeckgui\holodeckgui.sln</SOLUTION>
      <SOLUTION Project="Log" BuildConfig="Release">C:\source_code\commercial\OldVersions\Holodeck\v2_1_longhorn\holodeck\holodeckgui\holodeckgui.sln</SOLUTION>
      <SOLUTION Project="ReplacementLibrary" BuildConfig="Release">C:\source_code\commercial\OldVersions\Holodeck\v2_1_longhorn\holodeck\holodeckgui\holodeckgui.sln</SOLUTION>
      <SOLUTION Project="MagicLibrary" BuildConfig="Release">C:\source_code\commercial\OldVersions\Holodeck\v2_1_longhorn\holodeck\holodeckgui\holodeckgui.sln</SOLUTION>
      <SOLUTION Project="HoloScript" BuildConfig="Release">C:\source_code\commercial\OldVersions\Holodeck\v2_1_longhorn\holodeck\holodeckgui\holodeckgui.sln</SOLUTION>
      <SOLUTION Project="GuiSupport" BuildConfig="Release">C:\source_code\commercial\OldVersions\Holodeck\v2_1_longhorn\holodeck\holodeckgui\holodeckgui.sln</SOLUTION>
      <SOLUTION Project="CLRInterceptLib" BuildConfig="Release">C:\source_code\commercial\OldVersions\Holodeck\v2_1_longhorn\holodeck\replacement\replacement.sln</SOLUTION>
      <SOLUTION Project="DotNetCacheGen" BuildConfig="Release">C:\source_code\commercial\OldVersions\Holodeck\v2_1_longhorn\holodeck\holodeckgui\holodeckgui.sln</SOLUTION>
      <SOLUTION Project="HolodeckLib" BuildConfig="Release">C:\source_code\commercial\OldVersions\Holodeck\v2_1_longhorn\holodeck\holodeckgui\holodeckgui.sln</SOLUTION>
      <SOLUTION Project="LibraryExport" BuildConfig="Release">C:\source_code\commercial\OldVersions\Holodeck\v2_1_longhorn\holodeck\holodeckgui\holodeckgui.sln</SOLUTION>
      <SOLUTION Project="HolodeckGui" BuildConfig="Release">C:\source_code\commercial\OldVersions\Holodeck\v2_1_longhorn\holodeck\holodeckgui\holodeckgui.sln</SOLUTION>
      <SOLUTION Project="GenerateReplacementLibrary" BuildConfig="Release">C:\source_code\commercial\OldVersions\Holodeck\v2_1_longhorn\holodeck\replacement\replacement.sln</SOLUTION>
      <SOLUTION Project="NetCorruptLibrary" BuildConfig="Release">C:\source_code\commercial\OldVersions\Holodeck\v2_1_longhorn\holodeck\replacement\replacement.sln</SOLUTION>
      <SOLUTION Project="HeatDotNet" BuildConfig="Release">C:\source_code\commercial\OldVersions\Holodeck\v2_1_longhorn\holodeck\replacement\replacement.sln</SOLUTION>
      <SOLUTION Project="DotNetReplacementLibrary" BuildConfig="Release">C:\source_code\commercial\OldVersions\Holodeck\v2_1_longhorn\holodeck\replacement\replacement.sln</SOLUTION>
      <SOLUTION Project="SystemReplacementLibrary" BuildConfig="Release">C:\source_code\commercial\OldVersions\Holodeck\v2_1_longhorn\holodeck\replacement\replacement.sln</SOLUTION>
      <SOLUTION Project="SystemServiceProcessReplacementLibrary" BuildConfig="Release">C:\source_code\commercial\OldVersions\Holodeck\v2_1_longhorn\holodeck\replacement\replacement.sln</SOLUTION>
      <SOLUTION Project="SystemXMLReplacementLibrary" BuildConfig="Release">C:\source_code\commercial\OldVersions\Holodeck\v2_1_longhorn\holodeck\replacement\replacement.sln</SOLUTION>
      <SOLUTION Project="MSCorLibReplacementLibrary" BuildConfig="Release">C:\source_code\commercial\OldVersions\Holodeck\v2_1_longhorn\holodeck\replacement\replacement.sln</SOLUTION>
      <SOLUTION Project="Advapi32ReplacementLibrary" BuildConfig="Release">C:\source_code\commercial\OldVersions\Holodeck\v2_1_longhorn\holodeck\replacement\replacement.sln</SOLUTION>
      <SOLUTION Project="Kernel32ReplacementLibrary" BuildConfig="Release">C:\source_code\commercial\OldVersions\Holodeck\v2_1_longhorn\holodeck\replacement\replacement.sln</SOLUTION>
      <SOLUTION Project="WS2_32ReplacementLibrary" BuildConfig="Release">C:\source_code\commercial\OldVersions\Holodeck\v2_1_longhorn\holodeck\replacement\replacement.sln</SOLUTION>
      <SOLUTION Project="DotNetReplacementInstall" BuildConfig="Release">C:\source_code\commercial\OldVersions\Holodeck\v2_1_longhorn\holodeck\replacement\replacement.sln</SOLUTION>
      <SOLUTION Project="HolodeckConfig" BuildConfig="Release">C:\source_code\commercial\OldVersions\Holodeck\v2_1_longhorn\HolodeckConfig\HolodeckConfig.sln</SOLUTION>
    </BUILD_SOLUTIONS>
  </PRODUCT>
  <PRODUCT Name="Holodeck 2.1 Longhorn Trial" MajorVersion="2" MinorVersion="1" BuildNumber="212">
    <SOURCECONTROL>
      <EXECUTE Args="/C c:\source_code\commercial\OldVersions\Holodeck\v2_1_longhorn\Install\HolodeckEESetup\unmake_timetrial.bat">c:\windows\system32\cmd.exe</EXECUTE>
      <EXECUTE Args="/C c:\source_code\commercial\OldVersions\Holodeck\v2_1_longhorn\Install\HolodeckEESetup\make_trial.bat">c:\windows\system32\cmd.exe</EXECUTE>
    </SOURCECONTROL>
    <PATHS>
      <BUILDS_LOCATION>c:\builds;y:</BUILDS_LOCATION>
      <LOGS_LOCATION>c:\builds\BuildLogs</LOGS_LOCATION>
      <DEVENV_FILE>C:\Program Files\Microsoft Visual Studio .NET Whidbey\Common7\IDE\devenv.exe</DEVENV_FILE>
      <INSTALLSHIELD_SCRIPT>C:\source_code\commercial\OldVersions\Holodeck\v2_1_longhorn\Install\HolodeckEESetup\HolodeckEESetup.ism.cmd</INSTALLSHIELD_SCRIPT>
      <INSTALLSHIELD_OUTPUT>C:\source_code\commercial\OldVersions\Holodeck\v2_1_longhorn\Install\HolodeckEESetup\Media\CD ROM Media\Package\HolodeckEESetup.exe</INSTALLSHIELD_OUTPUT>
    </PATHS>
    <BUILDMAIL>
      <RECIPIENTS>akakrania@sisecure.com, bshirey@sisecure.com, jtaylor@sisecure.com, rwagner@sisecure.com, jbasirico@sisecure.com, jwhitehouse@sisecure.com</RECIPIENTS>
      <MAILSENDER Address="sibuilder@sisecure.com" SmtpServer="192.168.2.1" />
    </BUILDMAIL>
    <BUILD_SOLUTIONS>
      <SOLUTION Project="FileCorruptionGenerator" BuildConfig="Release">C:\source_code\commercial\OldVersions\Holodeck\v2_1_longhorn\holodeck\holodeckgui\holodeckgui.sln</SOLUTION>
      <SOLUTION Project="HeatDll" BuildConfig="Release">C:\source_code\commercial\OldVersions\Holodeck\v2_1_longhorn\holodeck\holodeckgui\holodeckgui.sln</SOLUTION>
      <SOLUTION Project="HeatApi" BuildConfig="Release">C:\source_code\commercial\OldVersions\Holodeck\v2_1_longhorn\holodeck\holodeckgui\holodeckgui.sln</SOLUTION>
      <SOLUTION Project="SiUtils" BuildConfig="Release">C:\source_code\commercial\OldVersions\Holodeck\v2_1_longhorn\holodeck\holodeckgui\holodeckgui.sln</SOLUTION>
      <SOLUTION Project="FunctionDatabase" BuildConfig="Release">C:\source_code\commercial\OldVersions\Holodeck\v2_1_longhorn\holodeck\holodeckgui\holodeckgui.sln</SOLUTION>
      <SOLUTION Project="Log" BuildConfig="Release">C:\source_code\commercial\OldVersions\Holodeck\v2_1_longhorn\holodeck\holodeckgui\holodeckgui.sln</SOLUTION>
